org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (see https://fabricmc.net/develop)
minecraft_version=1.21.11
# Latest Yarn build for 1.21.11 (resolved automatically)
yarn_mappings=1.21.11+build.+
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.0.0
group=net.servertools

# Dependencies
fabric_api_version=0.141.6+1.21.11
permissions_api_version=0.6.1
